# Generated by Django 6.0.2 on 2026-02-22 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date de passage",
                    ),
                ),
                (
                    "mileage_at_visit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kilometrage lors du passage",
                    ),
                ),
                (
                    "concern",
                    models.CharField(max_length=255, verbose_name="Motif principal"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Diagnostic")),
                (
                    "work_performed",
                    models.TextField(blank=True, verbose_name="Travaux effectues"),
                ),
                (
                    "technician_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Technicien"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouvert"),
                            ("IN_PROGRESS", "En cours"),
                            ("DONE", "Termine"),
                            ("CANCELED", "Annule"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cout estime",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cout reel",
                    ),
                ),
                (
                    "next_visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prochain passage suggere"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop_visits",
                        to="vehicles.vehicle",
                        verbose_name="Vehicule",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "-id"],
            },
        ),
    ]
