# Generated by Django 6.0.2 on 2026-03-02 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicle_customer"),
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opened_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date de maintenance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouverte"),
                            ("DONE", "Terminee"),
                            ("CANCELED", "Annulee"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Statut maintenance",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes maintenance"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="vehicles.vehicle",
                        verbose_name="Vehicule",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_on", "-id"],
            },
        ),
        migrations.AddField(
            model_name="workshopvisit",
            name="maintenance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="workshop.maintenance",
                verbose_name="Maintenance rattachee",
            ),
        ),
    ]
