# Generated by Django 6.0.2 on 2026-03-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0002_maintenance_workshopvisit_maintenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopvisit",
            name="service",
            field=models.CharField(
                choices=[
                    ("MECHANIQUE", "Mecanique"),
                    ("CLIMATISATION", "Climatisation"),
                    ("PNEUMATIQUES", "Pneumatiques"),
                    ("TOLERIE_SOUDURE", "Tolerie/soudure"),
                    ("ELECTRICITE", "Electricite"),
                    ("SCANNER_AUTO", "Scanner Auto"),
                ],
                default="MECHANIQUE",
                max_length=30,
                verbose_name="Service atelier",
            ),
        ),
    ]
