# Generated by Django 6.0.2 on 2026-03-02 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_workshopvisit_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopvisit",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AddField(
            model_name="workshopvisit",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date de debut"
            ),
        ),
    ]
