# Generated by Django 6.0.2 on 2026-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_workshopvisit_end_date_workshopvisit_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=80, verbose_name="Nom")),
                ("position", models.CharField(max_length=80, verbose_name="Poste")),
                ("contact", models.CharField(max_length=120, verbose_name="Contact")),
                (
                    "identification_number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="N° identification"
                    ),
                ),
                (
                    "atelier",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Atelier"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Technicien",
                "verbose_name_plural": "Techniciens",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
