# Generated by Django 6.0.2 on 2026-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0005_technician"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="atelier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MECHANIQUE", "Mecanique"),
                    ("CLIMATISATION", "Climatisation"),
                    ("PNEUMATIQUES", "Pneumatiques"),
                    ("TOLERIE_SOUDURE", "Tolerie/soudure"),
                    ("ELECTRICITE", "Electricite"),
                    ("SCANNER_AUTO", "Scanner Auto"),
                ],
                max_length=120,
                verbose_name="Atelier",
            ),
        ),
    ]
