# Generated by Django 6.0.2 on 2026-02-22 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_roles_and_profiles(apps, schema_editor):
    role_model = apps.get_model("users", "Role")
    profile_model = apps.get_model("users", "UserProfile")
    user_model = apps.get_model("auth", "User")

    default_roles = [
        ("DG", "Direction Generale"),
        ("ASSISTANT", "Assistant"),
        ("CHEF", "Chef Atelier"),
        ("TECH", "Technicien"),
        ("COMPTA", "Comptabilite"),
        ("STANDARD", "Standard"),
    ]
    role_by_code = {}
    for code, name in default_roles:
        role, _ = role_model.objects.get_or_create(code=code, defaults={"name": name})
        role_by_code[code] = role

    default_role = role_by_code.get("STANDARD")
    for user in user_model.objects.all():
        profile, created = profile_model.objects.get_or_create(user_id=user.id)
        if created and default_role:
            profile.role = default_role
            profile.save(update_fields=["role"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("portal_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="users.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("manage_users", "Can manage users, roles and permissions")
                ],
            },
        ),
        migrations.RunPython(seed_roles_and_profiles, migrations.RunPython.noop),
    ]
