# Generated by Django 6.0 on 2026-06-01 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° Facture')),
                ('destinataire_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom / Entreprise')),
                ('destinataire_adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('destinataire_tel', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('destinataire_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('destinataire_rccm_ncc', models.CharField(blank=True, max_length=100, verbose_name='RCCM / NCC')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('reference_client', models.CharField(blank=True, max_length=100, verbose_name='Référence client')),
                ('objet', models.CharField(blank=True, max_length=200, verbose_name='Objet')),
                ('bon_de_commande', models.CharField(blank=True, max_length=100, verbose_name='Bon de commande')),
                ('remise_globale', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Remise globale (FCFA)')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='TVA (%)')),
                ('acompte_verse', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Acompte versé (FCFA)')),
                ('conditions_paiement', models.TextField(blank=True, default='30 jours net à réception de facture / Chèque, virement ou espèces', verbose_name='Conditions de paiement')),
                ('penalites_retard', models.TextField(blank=True, default='Tout retard de paiement entraîne des pénalités de 1,5% par mois.', verbose_name='Pénalités de retard')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('PARTIAL', 'Partiellement payé'), ('PAID', 'Payé'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Qté')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('remise_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise %')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° Proforma')),
                ('destinataire_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom / Entreprise')),
                ('destinataire_adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('destinataire_tel', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('destinataire_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('destinataire_rccm_ncc', models.CharField(blank=True, max_length=100, verbose_name='RCCM / NCC')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('reference_client', models.CharField(blank=True, max_length=100, verbose_name='Référence client')),
                ('objet', models.CharField(blank=True, max_length=200, verbose_name='Objet')),
                ('bon_de_commande', models.CharField(blank=True, max_length=100, verbose_name='Bon de commande')),
                ('remise_globale', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Remise globale (FCFA)')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='TVA (%)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('CONVERTED', 'Converti en facture')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='customers.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture Proforma',
                'verbose_name_plural': 'Factures Proforma',
                'ordering': ['-date_emission', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.proforma', verbose_name="Proforma d'origine"),
        ),
        migrations.CreateModel(
            name='ProformaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Qté')),
                ('prix_unitaire', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.proforma')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
