# Generated by Django 6.0 on 2026-06-10 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° Bon de livraison')),
                ('destinataire_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom / Entreprise')),
                ('destinataire_adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('destinataire_tel', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('destinataire_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('destinataire_rccm_ncc', models.CharField(blank=True, max_length=100, verbose_name='RCCM / NCC')),
                ('date_livraison', models.DateField(default=django.utils.timezone.now, verbose_name='Date de livraison')),
                ('lieu_livraison', models.CharField(blank=True, max_length=300, verbose_name='Lieu de livraison')),
                ('reference_client', models.CharField(blank=True, max_length=100, verbose_name='Référence client')),
                ('objet', models.CharField(blank=True, max_length=200, verbose_name='Objet')),
                ('bon_de_commande', models.CharField(blank=True, max_length=100, verbose_name='Bon de commande')),
                ('transporteur', models.CharField(blank=True, max_length=200, verbose_name='Transporteur / Livreur')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PREPARED', 'Préparé'), ('DELIVERED', 'Livré'), ('RECEIVED', 'Réceptionné'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='customers.customer', verbose_name='Client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='invoices.invoice', verbose_name='Facture liée')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'ordering': ['-date_livraison', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Qté')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='Unité')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.deliverynote')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
