# Generated by Django 6.0 on 2026-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_deliverynote_bon_de_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteline',
            name='observation',
            field=models.CharField(blank=True, max_length=300, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='quantite_commandee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qté commandée'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='designation',
            field=models.CharField(max_length=300, verbose_name='Désignation / Description'),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Qté livrée'),
        ),
    ]
