# Generated by Django 6.0.2 on 2026-02-22 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Immatriculation",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        unique=True,
                        verbose_name="Numero de serie (VIN)",
                    ),
                ),
                ("make", models.CharField(max_length=80, verbose_name="Marque")),
                ("model", models.CharField(max_length=80, verbose_name="Modele")),
                (
                    "trim",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Finition"
                    ),
                ),
                (
                    "first_registration_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de 1ere mise en circulation",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("ESSENCE", "Essence"),
                            ("DIESEL", "Diesel"),
                            ("HYBRID", "Hybride"),
                            ("ELECTRIC", "Electrique"),
                            ("GPL", "GPL"),
                            ("OTHER", "Autre"),
                        ],
                        default="ESSENCE",
                        max_length=20,
                        verbose_name="Carburant",
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manuelle"),
                            ("AUTO", "Automatique"),
                            ("ROBOT", "Robotisee"),
                            ("OTHER", "Autre"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kilometrage actuel",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=40, verbose_name="Couleur"),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=120, verbose_name="Nom proprietaire"),
                ),
                (
                    "owner_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telephone proprietaire"
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email proprietaire"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes techniques"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["registration_number"],
            },
        ),
    ]
